[package]
name = "xena"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "340fa14657208c612a2a5348ef12014133cd9650"}
